/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_testndk_HelloWorld */

#ifndef _Included_com_testndk_HelloWorld
#define _Included_com_testndk_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
#undef com_testndk_HelloWorld_AUTO_HIDE
#define com_testndk_HelloWorld_AUTO_HIDE 1L
#undef com_testndk_HelloWorld_AUTO_HIDE_DELAY_MILLIS
#define com_testndk_HelloWorld_AUTO_HIDE_DELAY_MILLIS 3000L
#undef com_testndk_HelloWorld_TOGGLE_ON_CLICK
#define com_testndk_HelloWorld_TOGGLE_ON_CLICK 1L
#undef com_testndk_HelloWorld_HIDER_FLAGS
#define com_testndk_HelloWorld_HIDER_FLAGS 6L
/*
 * Class:     com_testndk_HelloWorld
 * Method:    messageFromNativeCode
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_testndk_HelloWorld_messageFromNativeCode
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
